### ISSUE TITLE
would you release the training code?

### ISSUE THREAD

**Issue by Nevaeh7** [workforai/UniLSeg#3]

**Comment by yongliu20** [comment]
We are considering organzing the training code and making it public. But since I've been busy lately, I haven't set a clear schedule yet. If you are in a hurry, you can refer to the code of "CRIS: CLIP-Driven Referring Image Segmentation" to design  dataset&training process. Our code is also based on that. Thank you for your interest and patience.

**Comment by Nevaeh7** [comment]
> We are considering organzing the training code and making it public. But since I've been busy lately, I haven't set a clear schedule yet. If you are in a hurry, you can refer to the code of "CRIS: CLIP-Driven Referring Image Segmentation" to design dataset&training process. Our code is also based on that. Thank you for your interest and patience.

Thanks your useful reply!
