### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by tg-Flipped** [workforai/UniLSeg#9]
Hi authors, thanks for your good work. 
Whether the training code be released?

**Comment by yongliu20** [comment]
Sorry for the late reply. We are considering organzing the training code and making it public. Since I've been busy lately, the current schedule is to release these code in July. If you are in a hurry, you can refer to the code of "CRIS: CLIP-Driven Referring Image Segmentation" to design dataset&training process. Our code is also based on that. Thank you for your interest and patience.
